runtime: nodejs14
service: api

env_variables:
  NODE_ENV: 'production'
  DB_HOST: '104.199.56.122'
  DB_PORT: 5432
  DB_USER: 'pipauls'
  DB_PASSWORD: '51ia@J*^O@Ro'
  DB_DATABASE: 'pipauls'
  DB_SOCKET: '/cloudsql/mybudgetpipauls:europe-west1:pipauls'

beta_settings:
  cloud_sql_instances: mybudgetpipauls:europe-west1:pipauls
